<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KRUKUAF" failures="2" tests="4" name="Test" time="135.701" errors="0" timestamp="2022-09-23T15:24:02 IST">
  <testcase classname="testpack.TestNGClass1" name="VerifyContactHelpCenter" time="2.868">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Messenger is not working expected [https://www.messenger.com] but found [https://www.messenger.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Messenger is not working expected [https://www.messenger.com] but found [https://www.messenger.com/]
at testpack.TestNGClass1.VerifyContactHelpCenter(TestNGClass1.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyContactHelpCenter -->
  <testcase classname="testpack.TestNGClass1" name="VerifyReturnToMessanger" time="24.283"/>
  <testcase classname="testpack.TestNGClass" name="VerifyContactHelpCenter" time="6.993">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Messenger is not working expected [https://www.messenger.com] but found [https://www.messenger.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Messenger is not working expected [https://www.messenger.com] but found [https://www.messenger.com/]
at testpack.TestNGClass.VerifyContactHelpCenter(TestNGClass.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyContactHelpCenter -->
  <testcase classname="testpack.TestNGClass" name="VerifyReturnToMessanger" time="4.366"/>
</testsuite> <!-- Test -->
